### ISSUE TITLE
[vote] all API calls take arguments in a single option parameter.

### ISSUE THREAD

**Issue by ezolenko** [screepers/POSIS#3]
For example: (ignore the actual properties) 

```
spawnCreep(opts: { pos: RoomPosition, bodyOptions: BodyPartConstant[][], memory?: any, priority: number });
```

Benefits: 
- Named arguments (better chance of breaking if anything changes)
- Extensibility
- No stupid `(undefined, undefined, "stuff")` to skip some optional arguments
- Destructuring

**Comment by AlinaNova21** [comment]
I'm not so sure about all APIs, but optional heavy APIs such as spawnCreep  sure

**Comment by ezolenko** [comment]
Let's say 1-2 params are normal, anything more converts to this?

**Comment by AlinaNova21** [comment]
That sounds good to me, as was pointed out in slack, we can use destructuring inside the function to have individual variables
Also, opts param shouldn't be optional in that case since there are required properties ;)

**Comment by ezolenko** [comment]
Yep, I fixed that part. Shouldn't be optional even if all args are optional.

**Comment by AlinaNova21** [comment]
Closed, this has been agreed upon adn implemented in recent commits
