### ISSUE TITLE
[vote] [spawn extension] creep body array is sorted by decreasing process preference

### ISSUE THREAD

**Issue by ezolenko** [screepers/POSIS#4]
First one is ideal, second one is slightly less so, etc.

Host doesn't have to honor it, but convention is that sort order represents client preferences.

**Comment by AlinaNova21** [comment]
My opinion, this should not be part of the standard itself, but could be encouraged as 'good practice' or something.

**Comment by ezolenko** [comment]
There is no reason to have a random sort, or for 2 processes to have different sort order.

Priority not necessarily means size, just process preference.

And by "setting it in standard" I mean mentioning it in a comment above the method.

**Comment by anisoptera** [comment]
Agree, it's just establishing that `[0]` is the position of the most preferred spawn, rather than `.last()`. Seems important enough for documentation.

**Comment by AlinaNova21** [comment]
I suggest it be added as a PR to README and/or comments in IPosisSpawnExtension.d.ts

**Comment by AlinaNova21** [comment]
Resolved in #13
